### ISSUE TITLE
RuntimeError when displaying large image in 3D

### ISSUE THREAD

**Issue by amedyukhina** [napari/napari#1100]
## 🐛 Bug

When I try to display a 500x1500x1500 image using 3D mode, napari crashes and returns  RuntimeError: Cannot SIZE object 545 because it does not exist

This issue does not occur if I display a smaller image (100x1500x1500).

## To Reproduce
```
import napari
from dask import array as da

img = da.random.randint(0, 100, size=(500, 1500, 1500), chunks=250, dtype=np.uint16)

with napari.gui_qt():
	v = napari.view_image(img, is_pyramid=False, contrast_limits=(0, 100), ndisplay=3)
```

Complete error message:

```
                                                                                                              
WARNING: Error drawing visual <Volume at 0x7f7e4c15f860>
---------------------------------------------------------------------------
GLError                                   Traceback (most recent call last)
~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/app/backends/_qt.py in paintGL(self)
    823         # (0, 0, self.width(), self.height()))
    824         self._vispy_canvas.set_current()
--> 825         self._vispy_canvas.events.draw(region=None)
    826 
    827 

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/util/event.py in __call__(self, *args, **kwargs)
    453                     continue
    454 
--> 455                 self._invoke_callback(cb, event)
    456                 if event.blocked:
    457                     break

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/util/event.py in _invoke_callback(self, cb, event)
    473             _handle_exception(self.ignore_callback_errors,
    474                               self.print_callback_errors,
--> 475                               self, cb_event=(cb, event))
    476 
    477     def _prepare_event(self, *args, **kwargs):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/util/event.py in _invoke_callback(self, cb, event)
    469     def _invoke_callback(self, cb, event):
    470         try:
--> 471             cb(event)
    472         except Exception:
    473             _handle_exception(self.ignore_callback_errors,

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/canvas.py in on_draw(self, event)
    215         # scheduling of further updates
    216         self._update_pending = False
--> 217         self._draw_scene()
    218 
    219     def render(self, region=None, size=None, bgcolor=None, crop=None):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/canvas.py in _draw_scene(self, bgcolor)
    264             bgcolor = self._bgcolor
    265         self.context.clear(color=bgcolor, depth=True)
--> 266         self.draw_visual(self.scene)
    267 
    268     def draw_visual(self, visual, event=None):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/canvas.py in draw_visual(self, visual, event)
    302                         else:
    303                             if hasattr(node, 'draw'):
--> 304                                 node.draw()
    305                                 prof.mark(str(node))
    306                 else:

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/visuals.py in draw(self)
     97         if self.picking and not self.interactive:
     98             return
---> 99         self._visual_superclass.draw(self)
    100 
    101 

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/visuals/visual.py in draw(self)
    441         try:
    442             self._program.draw(self._vshare.draw_mode,
--> 443                                self._vshare.index_buffer)
    444         except Exception:
    445             logger.warning("Error drawing visual %r" % self)

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/visuals/shaders/program.py in draw(self, *args, **kwargs)
     99         self.build_if_needed()
    100         self.update_variables()
--> 101         Program.draw(self, *args, **kwargs)
    102 
    103     def build_if_needed(self):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/program.py in draw(self, mode, indices, check_error)
    531 
    532         # Process GLIR commands
--> 533         canvas.context.flush_commands()

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/context.py in flush_commands(self, event)
    174                 fbo = 0
    175             self.shared.parser.parse([('CURRENT', 0, fbo)])
--> 176         self.glir.flush(self.shared.parser)
    177 
    178     def set_viewport(self, *args):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in flush(self, parser)
    570         """ Flush all current commands to the GLIR interpreter.
    571         """
--> 572         self._shared.flush(parser)
    573 
    574 

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in flush(self, parser)
    492             show = self._verbose if isinstance(self._verbose, str) else None
    493             self.show(show)
--> 494         parser.parse(self._filter(self.clear(), parser))
    495 
    496     def _filter(self, commands, parser):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in parse(self, commands)
    817 
    818         for command in commands:
--> 819             self._parse(command)
    820 
    821     def get_object(self, id_):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in _parse(self, command)
    787                 ob.set_data(*args)
    788             elif cmd == 'SIZE':  # VertexBuffer, IndexBuffer,
--> 789                 ob.set_size(*args)  # Texture[1D, 2D, 3D], RenderBuffer
    790             elif cmd == 'ATTACH':  # FrameBuffer, Program
    791                 ob.attach(*args)

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in set_size(self, shape, format, internalformat)
   1622             self._shape_formats = shape, format, internalformat
   1623             glTexImage3D(self._target, 0, internalformat, format,
-> 1624                          gl.GL_BYTE, shape[:3])
   1625 
   1626     def set_data(self, offset, data):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in glTexImage3D(target, level, internalformat, format, type, pixels)
   1571     depth, height, width = pixels
   1572     _gl.glTexImage3D(target, level, internalformat,
-> 1573                      width, height, depth, border, format, type, None)
   1574 
   1575 

~/anaconda3/envs/napari/lib/python3.6/site-packages/OpenGL/latebind.py in __call__(self, *args, **named)
     41             """
     42             try:
---> 43                 return self._finalCall( *args, **named )
     44             except (TypeError,AttributeError) as err:
     45                 if self._finalCall is None:

~/anaconda3/envs/napari/lib/python3.6/site-packages/OpenGL/wrapper.py in wrapperCall(*args)
    887                                     err.cArgs = cArguments
    888                                     err.pyArgs = pyArgs
--> 889                                     raise err
    890                                 return result
    891                             return wrapperCall

~/anaconda3/envs/napari/lib/python3.6/site-packages/OpenGL/wrapper.py in wrapperCall(*args)
    880                                 cArguments = pyArgs
    881                                 try:
--> 882                                     result = wrappedOperation( *cArguments )
    883                                 except ctypes.ArgumentError as err:
    884                                     err.args = err.args + (cArguments,)

~/anaconda3/envs/napari/lib/python3.6/site-packages/OpenGL/error.py in glCheckError(self, result, baseOperation, cArguments, *args)
    232                         result,
    233                         cArguments = cArguments,
--> 234                         baseOperation = baseOperation,
    235                     )
    236                 return result

GLError: GLError(
	err = 1285,
	description = b'out of memory',
	baseOperation = glTexImage3D,
	pyArgs = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		1500,
		1500,
		500,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		1500,
		1500,
		500,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_3D,
		0,
		GL_LUMINANCE,
		1500,
		1500,
		500,
		0,
		GL_LUMINANCE,
		GL_BYTE,
		None,
	)
)
WARNING: Error drawing visual <Volume at 0x7f7e4c15f860>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/app/backends/_qt.py in paintGL(self)
    823         # (0, 0, self.width(), self.height()))
    824         self._vispy_canvas.set_current()
--> 825         self._vispy_canvas.events.draw(region=None)
    826 
    827 

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/util/event.py in __call__(self, *args, **kwargs)
    453                     continue
    454 
--> 455                 self._invoke_callback(cb, event)
    456                 if event.blocked:
    457                     break

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/util/event.py in _invoke_callback(self, cb, event)
    473             _handle_exception(self.ignore_callback_errors,
    474                               self.print_callback_errors,
--> 475                               self, cb_event=(cb, event))
    476 
    477     def _prepare_event(self, *args, **kwargs):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/util/event.py in _invoke_callback(self, cb, event)
    469     def _invoke_callback(self, cb, event):
    470         try:
--> 471             cb(event)
    472         except Exception:
    473             _handle_exception(self.ignore_callback_errors,

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/canvas.py in on_draw(self, event)
    215         # scheduling of further updates
    216         self._update_pending = False
--> 217         self._draw_scene()
    218 
    219     def render(self, region=None, size=None, bgcolor=None, crop=None):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/canvas.py in _draw_scene(self, bgcolor)
    264             bgcolor = self._bgcolor
    265         self.context.clear(color=bgcolor, depth=True)
--> 266         self.draw_visual(self.scene)
    267 
    268     def draw_visual(self, visual, event=None):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/canvas.py in draw_visual(self, visual, event)
    302                         else:
    303                             if hasattr(node, 'draw'):
--> 304                                 node.draw()
    305                                 prof.mark(str(node))
    306                 else:

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/scene/visuals.py in draw(self)
     97         if self.picking and not self.interactive:
     98             return
---> 99         self._visual_superclass.draw(self)
    100 
    101 

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/visuals/visual.py in draw(self)
    441         try:
    442             self._program.draw(self._vshare.draw_mode,
--> 443                                self._vshare.index_buffer)
    444         except Exception:
    445             logger.warning("Error drawing visual %r" % self)

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/visuals/shaders/program.py in draw(self, *args, **kwargs)
     99         self.build_if_needed()
    100         self.update_variables()
--> 101         Program.draw(self, *args, **kwargs)
    102 
    103     def build_if_needed(self):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/program.py in draw(self, mode, indices, check_error)
    531 
    532         # Process GLIR commands
--> 533         canvas.context.flush_commands()

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/context.py in flush_commands(self, event)
    174                 fbo = 0
    175             self.shared.parser.parse([('CURRENT', 0, fbo)])
--> 176         self.glir.flush(self.shared.parser)
    177 
    178     def set_viewport(self, *args):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in flush(self, parser)
    570         """ Flush all current commands to the GLIR interpreter.
    571         """
--> 572         self._shared.flush(parser)
    573 
    574 

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in flush(self, parser)
    492             show = self._verbose if isinstance(self._verbose, str) else None
    493             self.show(show)
--> 494         parser.parse(self._filter(self.clear(), parser))
    495 
    496     def _filter(self, commands, parser):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in parse(self, commands)
    817 
    818         for command in commands:
--> 819             self._parse(command)
    820 
    821     def get_object(self, id_):

~/anaconda3/envs/napari/lib/python3.6/site-packages/vispy/gloo/glir.py in _parse(self, command)
    772                 if id_ not in self._invalid_objects:
    773                     raise RuntimeError('Cannot %s object %i because it '
--> 774                                        'does not exist' % (cmd, id_))
    775                 return
    776             # Triage over command. Order of commands is set so most

RuntimeError: Cannot SIZE object 545 because it does not exist

```

## Environment

napari: 0.2.11
Platform: Linux-4.15.0-88-generic-x86_64-with-debian-buster-sid
Python: 3.6.10 |Anaconda, Inc.| (default, Mar 25 2020, 23:51:54)  [GCC 7.3.0]
Qt: 5.14.2
PySide2: 5.14.2
VisPy: 0.6.4
NumPy: 1.18.2
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.13.0

GL version:  3.1 Mesa 19.2.8
MAX_TEXTURE_SIZE: 8192

**Comment by jni** [comment]
@amedyukhina thank you for reporting! To be honest, that is a pretty large volume to display in 3D. What is your GPU? I can't reproduce on my machine (integrated graphics, which I think means shared RAM with the CPU), but it's super slow. (Although rendering='translucent' speeds up the interactivity dramatically.) I would say on our end there is probably not much to do except maybe intercept this error and make it clearer.

On your side, I would suggest either resampling offline or doing so online with `da.coarsen`.

@tlambert03 any other suggestions?

**Comment by tlambert03** [comment]
yeah, you're definitely running out of memory. (As a sidenote, whenever you get those 
"`RuntimeError: Cannot SIZE object`" errors in vispy, it usually means the real error is buried somewhere higher up in the stack trace.  in this case it's this line):
```
GLError: GLError(
	err = 1285,
	description = b'out of memory',
```

but the explanation is still complicated: that last line of your `--info` return shows you the GL_MAX_TEXTURE_SIZE for your system: 8192.  As [described here](https://stackoverflow.com/questions/9758209/confusion-with-gl-max-texture-size), that basically means that the largest size array that your GPU/openGL is capable of handling is 8192x8192 = 67,108,864 pixels.  At 500x1500x1500 you're up to 1,125,000,000 pixels and well over the max.  (That said, I'll also point out that the smaller volume that you said worked is _still_ over the 67.1M pixels... so there's clearly more to the story).  In any case, you're maxing out your hardware.

In the short term, as @jni said, you'll need to figure out how to deliver less of the image at a time to the GPU.  Downsizing/resampling is the simplest approach here.  Longer term... one can imagine some approaches where might we try to use multi-resolution/pyramid approaches here, but that's particularly tricky in 3D as you "rotate" the image around interactively.

**Comment by amedyukhina** [comment]
Oh, I see. Thanks for explaining @tlambert03 !  I had no idea I could run out of memory since the machine that I used has 1.5Tb CPU memory (but apparently very little GPU memory).

> that is a pretty large volume to display in 3D

@jni this is actually just a small part of the volume that I work with and try to visualize (570x6900x10000). Apparently, I will have to switch to GPU-heavier hardware. 

Btw, thanks for developing such a great software! It works perfectly for smaller datasets.

**Comment by jni** [comment]
@amedyukhina unfortunately this is not a problem that can really be solved by bigger GPUs, as GPU memory is much more limited compared to CPU RAM. The best GPU you can buy only has 12GB of memory. The really fancy graphics engines work by loading subsampled, low-resolution images in the background, and high-resolution images only in the foreground. We don't have that in napari and I expect it'll take a long time to get there. So I'm afraid for now, with napari you are stuck looking at subvolumes, 2D slices, or low-resolution renderings.

**Comment by sofroniewn** [comment]
Leaving this open as it would be nice for napari to provide a better error message/ automatically downsample when this happens - right now we downsample only if an axis exceeds the max texture size, which has been hard coded to 2048 for 3D viewing https://github.com/napari/napari/blob/master/napari/_vispy/vispy_image_layer.py#L149

**Comment by sofroniewn** [comment]
I'm going to close this now. We do emit a warning when the requested data exceeds the texture size and downsample automatically. If this continues to cause issues feel free to reopen or create a new issue!!

**Comment by AdvancedImagingUTSW** [comment]
This is still a problem for me.  Even with 32GB of GPU RAM, cropping my data, and converting it to 8-bit.  File size of 1GB throws the error.  

Using the following modules (some of which are unrelated) on my RedHat Linux machine: 
```
module load python/3.8.x-anaconda
module load cuda112/blas/11.2.0
module load cuda112/fft/11.2.0
module load cuda112/toolkit/11.2.0
module load cudnn/8.1.1.33
```

Monitoring GPU memory with nvidia-smi -l 1 shows no spike in GPU memory or even GPU activity.

**Comment by Czaki** [comment]
> throws the error.

this issue is 2 year old. Napari codebase strongly change. Could you post stacktrace? Best will be if you could use last rc (`pip install -U --pre napari`). This may help us to solve this problem.

**Comment by AdvancedImagingUTSW** [comment]
Previously was running napari 0.4.15.  Updated to 0.4.16.rc2.  
Image size 1600 x 1600 x 900.  4.6GB.  
Worth noting, I think this may be a Linux-specific problem.  Later in the day yesterday I was able to render a similar sized image on a Windows-based machine, with a similar GPU.

Full stacktrace below.

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/app/backends/_qt.py:903, in CanvasBackendDesktop.paintGL(self=<vispy.app.backends._qt.CanvasBackendDesktop object>)
    901 # (0, 0, self.width(), self.height()))
    902 self._vispy_canvas.set_current()
--> 903 self._vispy_canvas.events.draw(region=None)
        self._vispy_canvas = <VispyCanvas (PyQt5) at 0x2aacb7be2880>
        self._vispy_canvas.events.draw = <vispy.util.event.EventEmitter object at 0x2aacb7c3a7f0>
        self = <vispy.app.backends._qt.CanvasBackendDesktop object at 0x2aacb7c460d0>
        self._vispy_canvas.events = <vispy.util.event.EmitterGroup object at 0x2aacb7c3a670>
    905 # Clear the alpha channel with QOpenGLWidget (Qt >= 5.4), otherwise the
    906 # window is translucent behind non-opaque objects.
    907 # Reference:  MRtrix3/mrtrix3#266
    908 if QT5_NEW_API or PYSIDE6_API or PYQT6_API:

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/util/event.py:453, in EventEmitter.__call__(self=<vispy.util.event.EventEmitter object>, *args=(), **kwargs={'region': None})
    450 if self._emitting > 1:
    451     raise RuntimeError('EventEmitter loop detected!')
--> 453 self._invoke_callback(cb, event)
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
        self = <vispy.util.event.EventEmitter object at 0x2aacb7c3a7f0>
        cb = <bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5) at 0x2aacb7be2880>>
    454 if event.blocked:
    455     break

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/util/event.py:471, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5)>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    469     cb(event)
    470 except Exception:
--> 471     _handle_exception(self.ignore_callback_errors,
        self = <vispy.util.event.EventEmitter object at 0x2aacb7c3a7f0>
        cb = <bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5) at 0x2aacb7be2880>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
        (cb, event) = (<bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5) at 0x2aacb7be2880>>, <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    472                       self.print_callback_errors,
    473                       self, cb_event=(cb, event))

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/util/event.py:469, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5)>>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    467 def _invoke_callback(self, cb, event):
    468     try:
--> 469         cb(event)
        cb = <bound method SceneCanvas.on_draw of <VispyCanvas (PyQt5) at 0x2aacb7be2880>>
        event = <DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>
    470     except Exception:
    471         _handle_exception(self.ignore_callback_errors,
    472                           self.print_callback_errors,
    473                           self, cb_event=(cb, event))

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/scene/canvas.py:218, in SceneCanvas.on_draw(self=<VispyCanvas (PyQt5)>, event=<DrawEvent blocked=False handled=False native=None region=None source=None sources=[] type=draw>)
    215 # Now that a draw event is going to be handled, open up the
    216 # scheduling of further updates
    217 self._update_pending = False
--> 218 self._draw_scene()
        self = <VispyCanvas (PyQt5) at 0x2aacb7be2880>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/scene/canvas.py:277, in SceneCanvas._draw_scene(self=<VispyCanvas (PyQt5)>, bgcolor=<class 'numpy.ndarray'> (4,) float32)
    275     bgcolor = self._bgcolor
    276 self.context.clear(color=bgcolor, depth=True)
--> 277 self.draw_visual(self.scene)
        self = <VispyCanvas (PyQt5) at 0x2aacb7be2880>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/scene/canvas.py:315, in SceneCanvas.draw_visual(self=<VispyCanvas (PyQt5)>, visual=<SubScene>, event=None)
    313         else:
    314             if hasattr(node, 'draw'):
--> 315                 node.draw()
        node = <Volume at 0x2aacbc72afa0>
    316                 prof.mark(str(node))
    317 else:

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/scene/visuals.py:103, in VisualNode.draw(self=<Volume>)
    101 if self.picking and not self.interactive:
    102     return
--> 103 self._visual_superclass.draw(self)
        self = <Volume at 0x2aacbc72afa0>
        self._visual_superclass = <class 'vispy.visuals.volume.VolumeVisual'>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/visuals/visual.py:451, in Visual.draw(self=<Volume>)
    449 self._configure_gl_state()
    450 try:
--> 451     self._program.draw(self._vshare.draw_mode,
        self._vshare.draw_mode = 'triangle_strip'
        self = <Volume at 0x2aacbc72afa0>
        self._vshare = <vispy.visuals.visual.VisualShare object at 0x2aacbc492820>
        self._program = <vispy.visuals.shaders.program.ModularProgram object at 0x2aacbb770670>
        self._vshare.index_buffer = <IndexBuffer size=14 last_dim=1>
    452                        self._vshare.index_buffer)
    453 except Exception:
    454     logger.warning("Error drawing visual %r" % self)

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/visuals/shaders/program.py:102, in ModularProgram.draw(self=<vispy.visuals.shaders.program.ModularProgram object>, *args=('triangle_strip', <IndexBuffer size=14 last_dim=1>), **kwargs={})
    100 self.build_if_needed()
    101 self.update_variables()
--> 102 Program.draw(self, *args, **kwargs)
        self = <vispy.visuals.shaders.program.ModularProgram object at 0x2aacbb770670>
        args = ('triangle_strip', <IndexBuffer size=14 last_dim=1>)
        kwargs = {}

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/gloo/program.py:526, in Program.draw(self=<vispy.visuals.shaders.program.ModularProgram object>, mode='triangle_strip', indices=<IndexBuffer size=14 last_dim=1>, check_error=True)
    522     raise TypeError("Invalid index: %r (must be IndexBuffer)" %
    523                     indices)
    525 # Process GLIR commands
--> 526 canvas.context.flush_commands()
        canvas = <VispyCanvas (PyQt5) at 0x2aacb7be2880>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/gloo/context.py:172, in GLContext.flush_commands(self=<GLContext>, event=None)
    170         fbo = 0
    171     self.shared.parser.parse([('CURRENT', 0, fbo)])
--> 172 self.glir.flush(self.shared.parser)
        self = <GLContext at 0x2aacb7c3a7c0>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/gloo/glir.py:582, in GlirQueue.flush(self=<vispy.gloo.glir.GlirQueue object>, parser=<vispy.gloo.glir.GlirParser object>)
    580 def flush(self, parser):
    581     """Flush all current commands to the GLIR interpreter."""
--> 582     self._shared.flush(parser)
        parser = <vispy.gloo.glir.GlirParser object at 0x2aacb7c3a940>
        self._shared = <vispy.gloo.glir._GlirQueueShare object at 0x2aacb7c3aa00>
        self = <vispy.gloo.glir.GlirQueue object at 0x2aacb7c3a9d0>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/gloo/glir.py:504, in _GlirQueueShare.flush(self=<vispy.gloo.glir._GlirQueueShare object>, parser=<vispy.gloo.glir.GlirParser object>)
    502     show = self._verbose if isinstance(self._verbose, str) else None
    503     self.show(show)
--> 504 parser.parse(self._filter(self.clear(), parser))
        self = <vispy.gloo.glir._GlirQueueShare object at 0x2aacb7c3aa00>
        parser = <vispy.gloo.glir.GlirParser object at 0x2aacb7c3a940>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/gloo/glir.py:822, in GlirParser.parse(self=<vispy.gloo.glir.GlirParser object>, commands=[('FUNC', 'glClearColor', 0.0, 0.0, 0.0, 1.0), ('FUNC', 'glClear', 17664), ('SIZE', 79, 96), ('DATA', 79, 0, <class 'numpy.ndarray'> (8, 1) [('f0', '<f4', (3,))]), ('SIZE', 82, 56), ('DATA', 82, 0, <class 'numpy.ndarray'> (14,) uint32), ('FUNC', 'glDisable', 'cull_face'), ('FUNC', 'glEnable', 'blend'), ('FUNC', 'glEnable', 'depth_test'), ('FUNC', 'glBlendFuncSeparate', 'src_alpha', 'one_minus_src_alpha', 'zero', 'one'), ('DRAW', 81, 'triangle_strip', (82, 'UNSIGNED_INT', 14))])
    819     self._objects.pop(id_)
    821 for command in commands:
--> 822     self._parse(command)
        command = ('SIZE', 79, 96)
        self = <vispy.gloo.glir.GlirParser object at 0x2aacb7c3a940>

File ~/.conda/envs/napari-env/lib/python3.9/site-packages/vispy/gloo/glir.py:778, in GlirParser._parse(self=<vispy.gloo.glir.GlirParser object>, command=('SIZE', 79, 96))
    776 if ob is None:
    777     if id_ not in self._invalid_objects:
--> 778         raise RuntimeError('Cannot %s object %i because it '
        'Cannot %s object %i because it '
                                       'does not exist' % (cmd, id_) = 'Cannot SIZE object 79 because it does not exist'
        cmd = 'SIZE'
        id_ = 79
        (cmd, id_) = ('SIZE', 79)
    779                            'does not exist' % (cmd, id_))
    780     return
    781 # Triage over command. Order of commands is set so most
    782 # common ones occur first.

RuntimeError: Cannot SIZE object 79 because it does not exist
```

**Comment by Czaki** [comment]
Strange. Whole statcktrace is from vispy. It will be nice to reproduce it on vispy standalone and then report in vispy repository.
@brisvag ?

**Comment by brisvag** [comment]
As @tlambert03 said above, when you get thiese "CAnnot SIZE object" errors in vispy, they are never the real error; you will find that higher up in the stack trace. This problem is likely completely unrelated to this issue, seeing how it's not cause by memory problems. Making these errors better is something we really need to tackle (I thought we had an issue open for this, but cnanot find it).

Please @AdvancedImagingUTSW, open a new issue and paste the full stack trace :)

**Comment by AdvancedImagingUTSW** [comment]
Opened a new issue. https://github.com/napari/napari/issues/4570#issue-1248261860

Feel free to close out this issue.
