### ISSUE TITLE
Color handling refactor

### ISSUE THREAD

**Issue by jni** [napari/napari#1356]
## 📚 Documentation

#1339 fixed a longstanding issue of directly mapping labels to colors. However, the parameter name "color_dict" is too restrictive in my opinion, since many color schemes can be conceived for labels. My suggestion is `colormap` which can be a callable mapping labels to colors, or a dict, or floats to colors, and could be in the future expanded to include e.g. an object that includes a GL shader to pass to vispy so that the full colormapping (labels -> graphics) can be done on the GPU, addressing #204 . 

This issue should be addressed before the next release so that we don't have to deprecate an API keyword shortly after introducing it.

**Comment by sofroniewn** [comment]
Ooo, sounds very intriguing @jni. Picking up on https://github.com/napari/napari/pull/1339#issuecomment-643723379

> I think this PR should be reworked to match more closely what @kevinyamauchi did with point colouring, but with the additional "random" mode to match existing behaviour. Specifically, there could be a "direct" mode that grabs the colour from a single property (it does not need to be named "color" @sofroniewn, it could have any name and be settable), "colormapped" that uses a colormap, or "auto"/"random" that uses the current behaviour.

The next plan for this chunk of work was going to be to support coloring based on properties, see some comments from @kevinyamauchi here https://github.com/napari/napari/pull/1339#issuecomment-639650482. If we could think from an API perspective what we'd like that to look like and then rename this kwarg appropriately so that we don't have to rename it again, I think that would be best.

I'm not so sure about `colormap` as in the `Image` layer which this subclasses `colormap` means one very specific thing and now we'd have it mean something more general. I will think on it more too.

> This issue should be addressed before the next release so that we don't have to deprecate an API keyword shortly after introducing it.

Agreed

**Comment by sofroniewn** [comment]
Looking at `Points` https://github.com/napari/napari/blob/master/napari/layers/points/_points_constants.py#L6-L15

```python
class ColorMode(StringEnum):
    """
    ColorMode: Color setting mode.
    DIRECT (default mode) allows each point to be set arbitrarily
    CYCLE allows the color to be set via a color cycle over an attribute
    COLORMAP allows color to be set via a color map over an attribute
    """
```

I read `DIRECT` mode as setting arbitrarily with the rgba array - which is why it is similar to the `color_dict` in `Labels` and that `COLORMAP` would be more akin to grabbing the color from a single property.

I guess stepping back what do I think we need:
- A place to store what color mode we're in
- Our autogenerated colormap
- A color dictionary based on labels
- A color dictionary based on properties.
- If we're using properties the name of the property that is being mapped to the dictionary if it is categorical (right now we don't really support this for points, we just support the cycle, but the dictionary approach might be more natural for string labeled categories too see comment in #1348

> In general, I find specifying the color_cycles via lists and then the mapping via zip(np.unique(values), color_cycle) not intuitive and think maps would make a lot more sense here.

Stepping back I think we should create a small dedicated `Color` object, thinking along the lines of #1343 that is completely reusable across `Points`, `Shapes`, `Vectors`, and `Labels`. For shapes we'd have two instantiations, one for `edge_color` and one for `face_color`. We'd then be able to access attributes like `color.map`, `color.mode`, `color.dict`, `color.contrast_limits` etc as needed. Note right now we have attributes like `face_color`, `face_color_cycle`, `face_colormap`, `face_contrast_limits` and it is all quite confusing and many things are duplicated or out of sync between our layers.

Thoughts @ziyangczi @jni @kevinyamauchi?

**Comment by kevinyamauchi** [comment]
Welcome back, @jni ! It's great seeing you all over github again :)

@sofroniewn, thank you for the proposal. I totally agree that the "flat" approach of attaching all properties to the layer model class is getting out of hand. When using these `Color` objects to store the color-related properties, would we still expose the individual properties in the `__init__` method? I would prefer that we avoid asking the user to instantiate and pass a `Color` object to the init method. I suppose an alternative would be to allow the user to pass a dictionary:

```python

# make a points layer where all points have the same color
layer = viewer.add_points(data, face_color='blue')

# make a points layer where each point has a different color
color_array = ['blue', 'green', 'magenta']
layer = viewer.add_points(data, face_color=color_array)

# make a points layer with each color property explicitly set
face_color = {
    'color': 'point_type',
    'mode': 'cycle',
    'cycle': ['magenta', 'blue', 'green']
}
properties = {'point_type': ['A', 'B', 'C']}
layer = viewer.add_points(data, properties=properties, face_color=face_color)

```

With this approach, it would also be pretty easy to keep the current kwargs in parallel (with a deprecation warning) so that people have time to change over to the new API.

Inline with what @jni that we probably want to propagate all of these changes to the other layers at once, as it's a pretty big breaking change. From my side, it would be helpful to plan out when we want to do this a bit so that I can make sure I can carve out some time.

Also super minor and we can decide this later, but I just wanted to note that we might want to choose a different name, as there is a [`Color` class in `vispy`](http://api.vispy.org/en/latest/color.html#vispy.color.Color).


> I'm not so sure about colormap as in the Image layer which this subclasses colormap means one very specific thing and now we'd have it mean something more general. I will think on it more too.

I'm just spitballing, but maybe `label_map` or `label_colormap`?

**Comment by jni** [comment]
> I would prefer that we avoid asking the user to instantiate and pass a Color object to the init method.

We are all on the same page. The `Color` object, which should be renamed to `ColorManager` or `ColorMapper` or similar rather than just `Color`, should remain private, at least in the beginning. As I've said many times before, I would like to keep the number low of new classes that people have to learn to use napari effectively.

I'm also hoping that we don't even have to deprecate the current approach, but let's see how these ideas evolve.

**Comment by liu-ziyang** [comment]
I agree with the spirit of the proposal: having a unified approach to manage colors, when I implemented the feature in question: adding a dictionary of colors, I was looking at Points layer and found it approaching colors differently. It might be due to them having a different characteristic of data requirements. Labeling requires a large area of data and using a color map with float would allow the representation of color in the least amount of space. while Pointing has less concern of data usage, and can use RGBA array to store the color information. This does create some difficulties when developers move from layer to layer as their need to relearn the coloring mechanism that is used in a specific layer.
However, this does seem to be some major refactor and requires more thought and planning. I doubt we can get a perfect solution within one release cycle

**Comment by sofroniewn** [comment]
As #1362 has now merged, and this issue has a good discussion about color refactoring more broadly I am going to leave it open but rename the issue to something more clear.

I really like the approach that @kevinyamauchi proposes where we "overload" the public API like that, but internally have an object that can handle the full range of possibilities with everything neatly organized. As @ziyangczi said, a bit more thought is probably needed in the design phase before jumping into the coding

**Comment by liu-ziyang** [comment]
Regarding the favored "Color" or "ColorManager" approach, I have a slightly related question: how many colors are really needed? by virtual I mean sure, there is practically an infinite amount of colors that a user can input with an RGBA array, but do we ever have a use case for that? given that when the colors are no longer distinguishable on screen. there is practically no point separating them since coloring is solely for display purposes. Wouldn't it make sense to restrict the color manager to a subset of colors, with names defined in a color dictionary? (Don't even get me to the mathematical [4 coloring theorm](https://en.wikipedia.org/wiki/Four_color_theorem) 😆 )

**Comment by sofroniewn** [comment]
> Wouldn't it make sense to restrict the color manager to a subset of colors, with names defined in a color dictionary?

We do support a couple named color dictionaries internally, see here for the XKCD colors that we vendor https://github.com/napari/napari/blob/master/napari/utils/colormaps/vendored/_color_data.py#L55 but we're also need to support hex values and people setting rgb values directly - I personally do that all the time for things like shades of gray where it is much more natural for me to think about the rgb values then remember what `light grey` or `dark grey` is.

In general our public API should allow most of https://matplotlib.org/3.1.0/gallery/color/color_demo.html. At that point having the internal representation as rgba seemed the most natural as you can always map into that space.

I see the `ColorManager` as being more about controlling the relationship between the data and how it is colored (i.e. colormap, color cycle, color dict, with properties/ random etc) rather than just about how we store color.

**Comment by JoeStrout** [comment]
So what was the outcome of this?  I am simply trying to set color 1 of my labels to appear green (rather than dark red), and I am completely lost in a twisty maze of issues and PRs, which discuss various options at great length.  And after reading all that, I still can't find a syntax that works.

Did this feature make it into Napari, and if so, how do I use it?

**Comment by Czaki** [comment]
@JoeStrout did you try syntax:

```python 
labels.layer.colormap = {1: "green"} 
```

(you need to set color for all labels, you may set a default color using `{1: "green", ..., None: "default_color"}`. 
you may use names of colors, hex colors or define it using float tuple `(0.5, 1, 1)`

**Comment by jni** [comment]
Yeah, this issue is a blast from the past and can be closed. There are now two syntaxes for dealing with colour labels:

```
viewer.layers.colormap = [c0, c1, c2, c3]  # set a colour cycle
viewer.layers.colormap = {1: c0, 2: c1, 3: c2, 4: c3}  # set a direct mapping
```

You can find an example of direct mapping in this example:

https://napari.org/stable/gallery/add_labels_with_features.html#sphx-glr-gallery-add-labels-with-features-py

direct link to code: 

https://github.com/napari/napari/blob/b2f722fd16e08d84cdf5f9af9cbd08b81639bf72/examples/add_labels_with_features.py#L50-L51

And I'm working on an example for the colour cycle in #7468. 

Sorry that it was hard to find @JoeStrout — we did indeed run into many issues while we were developing this so I can imagine it was hard to navigate after the fact!

I'm going to close the issue but do feel free to keep asking questions if anything else isn't clear! 🙏
