### ISSUE TITLE
Vispy Divided by Zero

### ISSUE THREAD

**Issue by Peter-Hogg** [napari/napari#3159]
## 🐛 Bug

When opening an image the thumbnail in the layer list will be displayed but the image won't be displayed in the Napari Window.  There seems to be an issue with the vispy camera. This issue only occurs on one machine. 

## To Reproduce

I ran the following code in a jupyter notebook:
viewer = napari.Viewer()
viewer.add_image(image[1, :, :], name="Microglia")

The image was an lsm file.

Error: Vispy tries to divide by zero:

E:\Anacada3\envs\caimgMG\lib\site-package\napari\_vispy\vispy_camera.py:109: RuntimeWaning: divide by zero encountered in true_divide
zoom = np.min(canvas_szie / scale)

WARNING: Error drawing visual <Image at 0x185879a0>

## Environment
Using Napari 0.4.10

## Additional context

Workings on my Ubuntu machine fine, doesn't work on my colleague's Windows machine. I'm uncertain what is causing this error.

**Comment by sofroniewn** [comment]
Thanks for flagging @Peter-Hogg! I think I may have seen this too. Maybe @DragaDoncila or @alisterburt can take a quick look for a fix

**Comment by alisterburt** [comment]
Hey! Thanks for the report @Peter-Hogg - I can't reproduce locally and I'm fairly sure this is the error that was fixed in #2958, we're aiming to put together a new release soon so hopefully this error will disappear once that release is out 🙂 

I'm a bit concerned by the `Error drawing visual`, the error that was fixed in #2958 produced an error but didn't affect rendering. If possible, could you install [napari master from source](https://napari.org/developers/contributing.html#setting-up-a-development-installation) and see if you still get these errors?

**Comment by DragaDoncila** [comment]
I can reproduce this locally with master (on mac and linux). Behaviour for me is different in that it still opens both thumbnail and layer - I've tried with labels and image layers.

Sample code:
```python
import napari
import numpy as np

viewer = napari.view_image(np.array([[1, 2]]))
napari.run()
```
or

```python
import napari
import numpy as np

viewer = napari.view_labels(np.array([[1, 2]]))
napari.run()
```

I will have a closer look at the conditions under which this warning does and doesn't occur, but I have to admit my familiarity with vispy is nonexistent.

**Comment by sofroniewn** [comment]
@DragaDoncila @alisterburt could it depend on what version of vispy one has? Maybe on latest vispy it is gone? It might be time to bump our vispy version dependency soon

**Comment by DragaDoncila** [comment]
@sofroniewn just upgraded vispy from 0.6.6 to 0.7.3 and the warning persists so I don't think it's vispy - unless you reckon it'll be fixed in the next release?

**Comment by sofroniewn** [comment]
> @sofroniewn just upgraded vispy from 0.6.6 to 0.7.3 and the warning persists so I don't think it's vispy - unless you reckon it'll be fixed in the next release?

No, was just a guess at why @DragaDoncila you might see something different from @alisterburt (if I am reading this thread right)

**Comment by DragaDoncila** [comment]
I've only been able to reproduce this message with layers where one dimension is a singleton e.g. a row or column of pixels, or just one pixel itself.

In these cases it occurs because the bounding corner of that dimension is still 0, and so `extent` [here](https://github.com/napari/napari/blob/49727940b479cbf6494570e5872c68509258078b/napari/components/viewer_model.py#L286) ends up with one dimension's size being 0  - hence the error.

We could fix this by checking whether the size of any dimension is 0, and if it is, just using the 95% canvas size approach from [here](https://github.com/napari/napari/blob/49727940b479cbf6494570e5872c68509258078b/napari/components/viewer_model.py#L301). @sofroniewn you're probably more familiar with this code than I am - does that seem like a reasonable suggestion?

I'm not sure whether that would fix @Peter-Hogg's issue though - @Peter-Hogg what are the dimensions of your image? I'm also not sure why the whole image won't load after the warning - the behaviour for me is that the image still opens. @Peter-Hogg do you have an example file you can share that produces this behaviour so I can see whether anything else is going on?

**Comment by Peter-Hogg** [comment]
I'll send you a test file when I get home today. What is the easiest way to share that? It's a fairly small file.

**Comment by alisterburt** [comment]
@Peter-Hogg a [gist](https://gist.github.com/) can be quite convenient, otherwise just copy and paste into a code block in a comment here! 🙂 thanks for delving into this @DragaDoncila

**Comment by Peter-Hogg** [comment]
https://gist.github.com/Peter-Hogg/b7beaae633ff2460a6d24fb532c77cf5

 Here is the notebook that generated the issue.  The shape of the images are as follows: (2, 2048, 2048). 

Here are few test files: https://osf.io/84f5k/

**Comment by DragaDoncila** [comment]
Ok after looking into it a bit further I'm confident the singleton dimension issue I described [above](https://github.com/napari/napari/issues/3159#issuecomment-900656581) is unrelated, despite the warning being the same.

@Peter-Hogg I've tried the files you shared and couldn't reproduce the error on `master`. What's weird is I also couldn't reproduce it on `0.4.10`. Would it be possible for you to [install napari from source](https://napari.org/developers/contributing.html#setting-up-a-development-installation) as @alisterburt suggested and see whether the error persists?

**Comment by Peter-Hogg** [comment]
I won't have access to the machine that is giving me the error for a day or two. I'll install from source and see if the error persists probably on Friday and post the results here.

**Comment by Peter-Hogg** [comment]
I was unable to install napari from source on that machine. I was getting errors with installing TensorStore when pip was installing some of the dependencies and the installation failed. My notebook works on my local Ubuntu machine but this Windows 7 machine is giving me a lot of problems. My only access to the machine is over Zoom when my colleagues screen shares from their Mac while they have remote access to the Windows box. It makes working on this a bit tricky

After reinstalling it with pip I got these errors: 

`E:\Anaconda3\envs\caimgMG\lib\site-packages\napari\_vispy\vispy_camera.py:109: RuntimeWarning: divide by zero encountered in true_divide
  zoom = np.min(canvas_size / scale)

<napari._qt.widgets.qt_viewer_dock_widget.QtViewerDockWidget at 0x1af4fdc0>

WARNING: Error drawing visual <Image at 0x1ac49490>

2021-08-20 09:26:55,270 [WARNING] Error drawing visual <Image at 0x1ac49490>

WARNING: Error drawing visual <Image at 0x1ac49490>`

**Comment by sofroniewn** [comment]
>  I was getting errors with installing TensorStore when pip was installing some of the dependencies and the installation failed

Looks like TensorStore is a test dependency for us - I do worry maybe we've gotten out of hand with out test dependencies - thoughts @jni?

 > My only access to the machine is over Zoom when my colleagues screen shares from their Mac while they have remote access to the Windows box. It makes working on this a bit tricky

Wow, nice work!

> `E:\Anaconda3\envs\caimgMG\lib\site-packages\napari_vispy\vispy_camera.py:109: RuntimeWarning: divide by zero encountered in true_divide

Huh ok sounds like it's still an issue

> We could fix this by checking whether the size of any dimension is 0, and if it is, just using the 95% canvas size approach from here. @sofroniewn you're probably more familiar with this code than I am - does that seem like a reasonable suggestion?

Yup could be ok if we fixed it there - alternatively we could just set `zoom = 1` instead of doing divide inside the camera file - it is definitely is not worse then the current behavior. I don't want to have to pass the canvas size to the camera, but otherwise either approach is fine. Thoughts @DragaDoncila @alisterburt, maybe @DragaDoncila you can make a PR with the best fix you see and add a test to capture that use case you identified above. Thanks!!

**Comment by DragaDoncila** [comment]
@sofroniewn , trying @Peter-Hogg's files with `master` on my Ubuntu machine, I do hit line 109 [here](https://github.com/napari/napari/blob/350e07cc5861005d6bb3199f8e39e276f8d04b3c/napari/_vispy/vispy_camera.py#L109) with `scale=[0,0]`, and the `if statement` added in #2958 changes it to `scale=[1, 1]`. If I comment out the two lines added in #2958, I do see the `RuntimeWarning` (though the image still opens). 

I'm very much leaning towards this being fixed on `master`, as @alisterburt suggested above. I think we may have to wait for a release though before @Peter-Hogg can test, because it sounds like installing from source won't be possible on the machine.

**Comment by sofroniewn** [comment]
> I'm very much leaning towards this being fixed on master, as @alisterburt suggested above. I think we may have to wait for a release though before @Peter-Hogg can test, because it sounds like installing from source won't be possible on the machine.

Ok I should make a release candidate tomorrow - which we can then test. thanks for the investigation here!

**Comment by sofroniewn** [comment]
@Peter-Hogg the napari `0.4.11rc3` release candidate is now available for testing - it can be installed with `pip install --pre napari -U`. If you can test this on your system and still see the warning do let us know! Hopefully this is all fixed now though!!

**Comment by psobolewskiPhD** [comment]
I'm not 100% sure this is the same bug, but in 4.11rc I still get divide by zero warnings.
For example, making a shapes layer:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2514: RuntimeWarning: divide by zero encountered in true_divide!
```
Everything functions, but the lil pop does show up in Napari.
I used to get errors when opening images, that's solved.

Napari Info:
<details>
napari: 0.4.11rc3
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- 3 Utilities: 0.1.4
- 4 Measurements (skimage): 0.1.4
- StarDist: 2021.6.28
- aicsimageio-in-memory: 0.3.5
- aicsimageio-out-of-memory: 0.3.5
- animation: 0.0.2
- clEsperanto: 0.9.10
- console: 0.0.4
- ome-types: 0.2.6
- scikit-image: 0.4.11rc3
- svg: 0.1.5
- video
</details>

**Comment by DragaDoncila** [comment]
Hi @psobolewskiPhD thanks for following up on this.

> For example, making a shapes layer

Is this when you make a brand new empty layer? Is it from existing data? If so what type of data, what shape is it?

I've seen this when opening single columns or single rows of pixels, but I don't remember having ever seen it for `Shapes`. A minimal example would be awesome.

**Comment by psobolewskiPhD** [comment]
In 4.11rc3:
Brand new, just clicking the Shapes layer icon to open it.
1. File > Open Sample > skimage > Astronaut (or StarDist 2D)
2. Click shapes layer icon in the layer list to make a shapes layer.

The warning actually fires twice:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2514: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2514: RuntimeWarning: divide by zero encountered in true_divide!
```

In 4.10:
Opening the sample gives a warning:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-env/lib/python3.9/site-packages/napari/_vispy/vispy_camera.py:109: RuntimeWarning: divide by zero encountered in true_divide!
```
(so this no longer happens in 4.11rc3)
and then clicking Shapes layer gives the same double warning as above.

**Comment by Peter-Hogg** [comment]
> @Peter-Hogg the napari `0.4.11rc3` release candidate is now available for testing - it can be installed with `pip install --pre napari -U`. If you can test this on your system and still see the warning do let us know! Hopefully this is all fixed now though!!

I'll try to test it on Friday! Thanks Nicholas and everyone

**Comment by sofroniewn** [comment]
> Brand new, just clicking the Shapes layer icon to open it.

I cannot reproduce this, really not sure what's going on here.

**Comment by grlee77** [comment]
@DragaDoncila said:

> I've only been able to reproduce this message with layers where one dimension is a singleton e.g. a row or column of pixels, or just one pixel itself.

Should we open a separate issue for this singleton case as it seems a different problem than the original issue here? I noticed the singleton issue when playing with 3D data that is size 1 along the slice axis. Upon opening the file I get:
```
napari/components/viewer_model.py:285: RuntimeWarning: divide by zero encountered in true_divide
      np.array(self._canvas_size) / np.array(size[-2:])
```
The underlying issue here is that size is 0 along one axis (`Viewer._sliced_extent_world` is size 0 on the last axis).

And if I transpose the axes in the 2D view so that the singleton dimension corresponds to the slider axis, then the slider disappears (I suppose this is as expected given there are no other slices to slide to) and the message is:
```
napari/_vispy/vispy_camera.py:111: RuntimeWarning: divide by zero encountered in true_divide
    zoom = np.min(canvas_size / scale)
```
where some debugging confirms that `scale = [239.57143095   0.        ]` and the value of 0.0 corresponds to `self._view.camera.rect.height`.

Despite these warnings, the data does load and I am able to interact with it as expected.

#2875 addressed the case where `scale == [0, 0]`, but in my case only one of the two values is zero.

**Comment by sofroniewn** [comment]
This should now hopefully be fixed by #3320 which is out in `0.4.11rc4`

**Comment by Peter-Hogg** [comment]
> > @Peter-Hogg the napari `0.4.11rc3` release candidate is now available for testing - it can be installed with `pip install --pre napari -U`. If you can test this on your system and still see the warning do let us know! Hopefully this is all fixed now though!!
> 
> I'll try to test it on Friday! Thanks Nicholas and everyone

I was able to test it last Friday and the divide by zero printout is gone

**Comment by kevinyamauchi** [comment]
Thanks for testing, @Peter-Hogg !
