### ISSUE TITLE
[Qt6 pyside6 6.5] TypeError on start

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5703]
## 🐛 Bug

Trying to launch napari from command line with pyside6==6.5.0 fails with an error:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-test/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/piotrsobolewski/Dev/napari/napari/__main__.py", line 566, in main
    _run()
  File "/Users/piotrsobolewski/Dev/napari/napari/__main__.py", line 326, in _run
    viewer = Viewer()
  File "/Users/piotrsobolewski/Dev/napari/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_main_window.py", line 589, in __init__
    self._qt_viewer.dockLayerList, tabify=False, menu=self.window_menu
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_viewer.py", line 357, in dockLayerList
    layerListLayout.addWidget(self.layers)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_viewer.py", line 335, in layers
    self._layers = QtLayerList(self.viewer.layers)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/containers/qt_layer_list.py", line 46, in __init__
    super().__init__(root, parent)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/containers/qt_list_view.py", line 43, in __init__
    self.setRoot(root)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/containers/_base_item_view.py", line 87, in setRoot
    self.setModel(create_model(root, self))
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/containers/_factory.py", line 72, in create_model
    return QtLayerListModel(obj, parent=parent)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/containers/_base_item_model.py", line 80, in __init__
    super().__init__(parent=parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

## To Reproduce

1. make fresh conda env (python 3.10)
2. pip install pyside6 (will yield 6.5.0
3. pip install -e . (napari from main)
4. try to launch using `napari`

## Expected behavior

Should work

## Environment

macOS 13.2.1, arm64, python 3.10, napari from main, pyside6 6.5.0 from pip
Edit: update: also occurs with 13.3.1, python 3.11.3, pyside 6.5.1

## Additional context

This is also reflected in failing tests, see: https://github.com/napari/napari/pull/5702
Some discussion here:
https://github.com/pyapp-kit/app-model/issues/93
and https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Qt.206.2E5

**Comment by Czaki** [comment]
It looks like it is working with PyQt6, so the problem is only touching PySide6.

**Comment by psobolewskiPhD** [comment]
It looks like this is a pyside6 6.5 bug
https://bugreports.qt.io/browse/PYSIDE-2294
and it looks like a fix has been merged:
https://codereview.qt-project.org/c/pyside/pyside-setup/+/471544

**Comment by psobolewskiPhD** [comment]
pyside6 6.5.1 is live on pypi, but alas this issue is still not fixed. I guess need to wait for 6.6.0?

**Comment by Czaki** [comment]
@hmaarrfk as you switch to pyside6 in deepcutlab you may be interested in tracing this Issue.

**Comment by hmaarrfk** [comment]
(not officially involved with deeplabcut but thanks for the ping)

Lets see if we can backport the patch: https://github.com/conda-forge/pyside2-feedstock/pull/191

**Comment by hmaarrfk** [comment]
The patch has already been applied in 6.5.1 
https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/shiboken6/libshiboken/bindingmanager.cpp?h=v6.5.1#n429

but it seems like the issue is not resolved :(

**Comment by hmaarrfk** [comment]
To recreate the PySide6 issue

```python
from PySide6.QtWidgets import QApplication, QMainWindow, QLabel
from typing import Generic, TypeVar

ItemType = TypeVar("ItemType")


class MainWindow(QMainWindow, Generic[ItemType]):
    def __init__(self):
        QMainWindow.__init__(self, parent=None)
        self.resize(400, 300)
        self.lbl = QLabel(self)
        self.lbl.setText("XXX")


app = QApplication([])
window = MainWindow()
window.show()
app.exec()
```


now i need to figure out their issue reporting system.

**Comment by psobolewskiPhD** [comment]
I think this pyside issue seems relevant here:
https://bugreports.qt.io/browse/PYSIDE-2304

**Comment by hmaarrfk** [comment]
Maybe, Issue 2354 has been getting good attention. The developers translated my example and adapted it for their internal validation and reuploaded it. so i'm pretty confident that there will be some improvement.

**Comment by psobolewskiPhD** [comment]
Small update: 
Newly released: PySide6 Version: 6.5.1.1
doesn't address this.

**Comment by psobolewskiPhD** [comment]
> I think this pyside issue seems relevant here:
> [bugreports.qt.io/browse/PYSIDE-2304](https://bugreports.qt.io/browse/PYSIDE-2304)

I checked and the solution suggested there (shaping the order), does work:
`class _BaseEventedItemModel(Generic[ItemType], QAbstractItemModel):`
everything seems to work, tests pass with pyqt5, but still have the test segfaults from https://github.com/napari/napari/issues/5657

**Comment by psobolewskiPhD** [comment]
I happen to notice that in this superqt pr:
[pyapp-kit/superqt@`a8e7d0f` (#154)](https://github.com/pyapp-kit/superqt/pull/154/commits/a8e7d0fbaa88907d3b7cbfb5e0893222c5202c48)
@dalthviz swapped the class inheritance order to fix pyside6 6.5.0 behavior.
Daniel, perhaps you can chime in here regarding the possible fix above?

**Comment by psobolewskiPhD** [comment]
Thanks @dalthviz 
I think maybe we should take the same approach in napari, so we can test on pyside >6.5

**Comment by MMathisLab** [comment]
Hi all 👋 - thanks for your efforts here. It's currently a big blocker for us at deeplabcut, so if our dev team can allocate time/efforts please let us know and cc @jeylau ❤️

**Comment by hmaarrfk** [comment]
>  class _BaseEventedItemModel(Generic[ItemType], QAbstractItemModel):

Would swapping the order of the subclasses be acceptable for napari? The presumption is that it would be accompanied with a comment as to why this is important for PySide6.

**Comment by Czaki** [comment]
@hmaarrfk Did you test that this works? The multiple inheritance with QObject is not trivial.

**Comment by hmaarrfk** [comment]
It seems really promising, but if the approach is a non-starter, then I don't think it makes sense for myself, or @MMathisLab or @jeylau to spend the time to validate futher than this screenshot

![image](https://github.com/napari/napari/assets/90008/169e0076-893c-49bf-9dd5-950cd68916f6)

Dependencies installed using conda-forge and screenshot taken on Ubuntu 22.04 on X11.

Napari started with the command

```
QT_API=PySide6 napari
```

**Comment by Czaki** [comment]
Right now, I don't see any problem with this approach. Maybe @brisvag knows something more about any problem. 

(I will be less available in the following week so any review PR may be delayed)

**Comment by psobolewskiPhD** [comment]
I have a branch with the swap of position and it seems to work fine.
However, we hit a different issue: https://github.com/napari/napari/issues/5657
I will make a PR, but I expect that tests will fail.

**Comment by psobolewskiPhD** [comment]
Here's the branch: https://github.com/napari/napari/pull/6062
Tests pass prior to bumping CI to pyside6 6.5.1.1, so I don't think it broke anything.
napari runs normally for me locally, but even locally the viewer tests crash as noted in 
https://github.com/napari/napari/issues/5657

**Comment by hmaarrfk** [comment]
Ok building 6.5.1.1 https://github.com/conda-forge/pyside2-feedstock/pull/195 to help with testing.

**Comment by psobolewskiPhD** [comment]
Just as an update, pyside6 6.5.2 was released and this issue remains.
The fix in https://github.com/napari/napari/pull/6062 still works, but alas so do the test failures from https://github.com/napari/napari/issues/5657

**Comment by dalthviz** [comment]
Hi there, just in case, checked this with latest pyside6 (6.7.0) and now I'm able to launch napari from latest main ( f9773dbdb) without doing any changes :tada: !

* napari info:

<details>

```
napari: 0.5.0a2.dev626+ge0c5c220
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Qt: 6.7.0
PySide6: 
NumPy: 1.25.2
SciPy: 1.9.3
Dask: 2023.10.1
VisPy: 0.14.1
magicgui: 0.7.3
superqt: 0.5.0
in-n-out: 0.2.0
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
- GL version: 4.5.0 - Build 25.20.100.6444
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1366x768, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Optional:
- numba: 0.58.1
- triangle not installed

Settings path:
- C:\Users\dalth\AppData\Local\napari\napari-dev_4454fdbf170edefe23827a4bf512389a6806af69\settings.yaml
```

</details>

However, I'm still able to reproduce #5657 Also, I tried adding layers and removing them continuosly and at some point that causes the application to crash :/ 

![crash](https://github.com/napari/napari/assets/16781833/93b8bef3-5d23-4c9b-bb7b-9a1d0ed25669)

**Comment by psobolewskiPhD** [comment]
Hmmm, progress? 🤣
They mention some known issues and soon-to-come 6.7.1
https://wiki.qt.io/Qt_for_Python_Development_Notes

**Comment by dalthviz** [comment]
> Odd that there isn't anything printed? segfault?

Yep, a segfault is my guess :+1:

> I think there's some odd behaviors with removing layers where they are partially maintained -- like if you watch RAM.
And you're going pretty fast, so maybe this is a corner case that's not horrible in reality? 🤔

Yep, I don't think a user will trigger a crash in that way so easly. It just ocurred to me, while thinking about the operations a test does on teardown, to check what would happen if you try to do a quick layer removal and indeed napari crashed 😅

**Comment by psobolewskiPhD** [comment]
I think we can consider this specific issue fixed with pyside6 6.7
The seg fault issue has it's own issue, so I will close this.
