### ISSUE TITLE
[0.4.11] Adjusting contrast results in a `TypeError`

### ISSUE THREAD

**Issue by Modjular** [napari/napari#5799]
## 🐛 Bug

When attempting to right click on the `contrast limits` slider to access detailed popup, a `TypeError` occurs
## To Reproduce

1. Open any file in napari
2. Go up to `contrast limits` slider in the `layer controls` panel
3. Right-click on the slider

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/miniconda3/lib/python3.10/site-packages/napari/_qt/layer_controls/qt_image_controls_base.py:37, in _QDoubleRangeSlider.mousePressEvent(self=, event=)
     26 """Update the slider, or, on right-click, pop-up an expanded slider.
     27 
     28 The expanded slider provides finer control, directly editable values,
   (...)
     34     The napari event that triggered this method.
     35 """
     36 if event.button() == Qt.RightButton:
---> 37     self.parent().show_clim_popupup()
        self = 
     38 else:
     39     super().mousePressEvent(event)

File ~/miniconda3/lib/python3.10/site-packages/napari/_qt/layer_controls/qt_image_controls_base.py:205, in QtBaseImageControls.show_clim_popupup(self=)
    203 self.clim_popup = QContrastLimitsPopup(self.layer, self)
    204 self.clim_popup.setParent(self)
--> 205 self.clim_popup.move_to('top', min_length=650)
        self.clim_popup = 
        self = 
    206 self.clim_popup.show()

File ~/miniconda3/lib/python3.10/site-packages/napari/_qt/dialogs/qt_modal.py:159, in QtPopup.move_to(self=, position='top', win_ratio=0.9, min_length=650)
    153 left = max(
    154     min(screen_geometry.right() - width, left), screen_geometry.left()
    155 )
    156 top = max(
    157     min(screen_geometry.bottom() - height, top), screen_geometry.top()
    158 )
--> 159 self.setGeometry(left, top, width, height)
        left = -99.39999999999998
        top = -1031
        width = 1360.8
        height = 67
        self = 

TypeError: arguments did not match any overloaded call:
  setGeometry(self, QRect): argument 1 has unexpected type 'float'
  setGeometry(self, int, int, int, int): argument 1 has unexpected type 'float'
```
## Expected behavior

I expect the slider details popup to appear

## Environment

```
napari: 0.4.11
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.10 (main, Mar 21 2023, 13:41:05) [Clang 14.0.6 ]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.3.2
VisPy: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1512x982, scale 2.0
  - screen 2: resolution 1080x1920, scale 1.0
  - screen 3: resolution 1920x1080, scale 1.0

Plugins:
  - console: 0.0.8
  - napari-brightness-contrast: 0.1.8
  - napari-tools-menu: 0.1.19
  - scikit-image: 0.4.11
  - svg: 0.1.6
```

```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	8 (6 performance and 2 efficiency)
  Memory:	16 GB
  System Firmware Version:	7459.141.1
  OS Loader Version:	7459.141.1
  Serial Number (system):	LNPN7LV2PN
  Hardware UUID:	E813E866-831D-5752-8A99-0A954F0F01ED
  Provisioning UDID:	00006000-000C28DC0121801E
  Activation Lock Status:	Enabled
```

## Additional context
Installed via `conda`. This was not my first attempt at installing `napari`. The bundled installer and `pip install` both failed. I'm assuming a big part is due to Apple Silicon.

**Comment by Modjular** [comment]
This was addressed in 2021: https://github.com/napari/napari/pull/3687

Any idea how to update to the latest version? I was only (barely) able to get `napari` working on my M1 via `conda`. 
In the [suggested installation](https://github.com/napari/napari/pull/3687) section:

> If you prefer to manage packages with conda, napari is available on the conda-forge channel. You can install it with:
> 
>     conda install -c conda-forge napari
> 
> You can then upgrade to a new version of napari using
> 
>     conda update napari

However, upgrading leaves me at `0.4.11`. Is `conda-forge` not on the latest? Is there a way to force update?

**Comment by jni** [comment]
Hmm, this is probably an issue with your conda environment. 0.4.17 is available on conda-forge. You should be able to do `conda install -c conda-forge napari=0.4.17`. There might be a conflict with some other package you specified earlier in your environment's history, in which case, I recommend starting a new environment from scratch.

I'm going to close this as the issue itself is resolved, but feel free to keep the conversation going and we'll be glad to help as much as we can with your install/env issues!

**Comment by Modjular** [comment]
@jni `conda install -c conda-forge napari=0.4.17` did the trick! Thanks so much. I still don't know why `conda` was defaulting to `0.4.11`.

**Comment by Czaki** [comment]
conda prefers to not update already installed libraries. Maybe of napari dependencies was in a version compatible with 0.4.11 and not newer. 

so conda prefer to install napari 0.4.11 instead of updating this dependency.
