### ISSUE TITLE
Segmentation fault wen trying to start Napari viewer from script

### ISSUE THREAD

**Issue by sebi06** [napari/napari#729]
## 🐛 Bug

When I try to start the Napari Viewer (latest version) from a script on Ubunto 18.04.3 LTS I recently got: **Segmentation fault** 

## To Reproduce

The relevant lines of code are here and I think the error occue

```
def show_napari(array, metadata,
                blending='additive',
                gamma=0.45,
                verbose=True):

    with napari.gui_qt():

        # create scalefcator with all ones
        scalefactors = [1] * len(array.shape)

        # initialize the napari viewer
        viewer = napari.Viewer()

        if metadata['ImageType'] == 'ometiff':

            # find position of dimensions
            posZ = metadata['DimOrder BF Array'].find('Z')
            posC = metadata['DimOrder BF Array'].find('C')
            posT = metadata['DimOrder BF Array'].find('T')

            # get the scalefactors from the metadata
            scalef = get_scalefactor(metadata)
            # modify the tuple for the scales for napari
            scalefactors[posZ] = scalef['zx']

            if verbose:
                print('Dim PosT : ', posT)
                print('Dim PosC : ', posC)
                print('Dim PosZ : ', posZ)
                print('Scale Factors : ', scalefactors)

            # add all channels as layers
            for ch in range(metadata['SizeC']):

                try:
                    # get the channel name
                    chname = metadata['Channels'][ch]
                except:
                    # or use CH1 etc. as string for the name
                    chname = 'CH' + str(ch + 1)

                # cutout channel
                channel = array.take(ch, axis=posC)
                print('Shape Channel : ', ch, channel.shape)

                # actually show the image array
                print('Scaling Factors: ', scalefactors)

                # get min-max values for initial scaling
                clim = [channel.min(), np.round(channel.max() * 0.85)]
                if verbose:
                    print('Scaling: ', clim)
                viewer.add_image(channel,
                                 name=chname,
                                 scale=scalefactors,
                                 contrast_limits=clim,
                                 blending=blending,
                                 gamma=gamma)

        if metadata['ImageType'] == 'czi':

            # find position of dimensions
            posZ = metadata['Axes'].find('Z')
            posC = metadata['Axes'].find('C')
            posT = metadata['Axes'].find('T')

            # get the scalefactors from the metadata
            scalef = get_scalefactor(metadata)
            # modify the tuple for the scales for napari
            scalefactors[posZ] = scalef['zx']

            if verbose:
                print('Dim PosT : ', posT)
                print('Dim PosZ : ', posZ)
                print('Dim PosC : ', posC)
                print('Scale Factors : ', scalefactors)

            if metadata['SizeC'] > 1:
                # add all channels as layers
                for ch in range(metadata['SizeC']):

                    try:
                        # get the channel name
                        chname = metadata['Channels'][ch]
                    except:
                        # or use CH1 etc. as string for the name
                        chname = 'CH' + str(ch + 1)

                    # cut out channel
                    channel = array.take(ch, axis=posC)
                    print('Shape Channel : ', ch, channel.shape)

                    # actually show the image array
                    print('Adding Channel: ', chname)
                    print('Scaling Factors: ', scalefactors)

                    # get min-max values for initial scaling
                    clim = [channel.min(), np.round(channel.max() * 0.85)]
                    if verbose:
                        print('Scaling: ', clim)
                    viewer.add_image(channel,
                                     name=chname,
                                     scale=scalefactors,
                                     contrast_limits=clim,
                                     blending=blending,
                                     gamma=gamma)

            if metadata['SizeC'] == 1:

                ch = 0
                # just add one channel as a layer
                try:
                        # get the channel name
                    chname = metadata['Channels'][ch]
                except:
                    # or use CH1 etc. as string for the name
                    chname = 'CH' + str(ch + 1)

                # actually show the image array
                print('Adding Channel: ', chname)
                print('Scaling Factors: ', scalefactors)

                # get min-max values for initial scaling
                clim = [channel.min(), np.round(channel.max() * 0.85)]
                if verbose:
                    print('Scaling: ', clim)
                viewer.add_image(array,
                                 name=chname,
                                 scale=scalefactors,
                                 contrast_limits=clim,
                                 blending=blending,
                                 gamma=gamma)
```
This is the output when I call the script:

![image](https://user-images.githubusercontent.com/3833249/69498681-e9733880-0eea-11ea-8844-4be37cfea7d5.png)

## Expected behavior

No Segmentation fault

## Environment

I used the latest version (24.11.2019) of Napari from GitHub and installed it via

`pip install -e .`

**Comment by AhmetCanSolak** [comment]
Hi @sebi06 !

Thank you for dropping an issue. Have you tried with latest version on pypi? just curious.

**Comment by jni** [comment]
@sebi06 would you be able to share your image and metadata so that we can try to reproduce the error? Thanks!

**Comment by sofroniewn** [comment]
This might relate to #576 which has been fixed on the latest version of vispy on GitHub (which they havn't released yet), so if you install vispy from GitHub and `pip install -e .` I'm curious if the error still persists. They should be releasing pretty soon, so we can get this fix to everyone.

Both the latest napari on pypi and the napari on master should behave the same way with respect to #576

**Comment by zeissmicroscopy** [comment]
Hi guys, I also tried the same on my windows 10 machine and there the code works fine. You can try to reproduce it by using this script:

[Read_OMETIFF_or_CZI.py](https://github.com/sebi06/ipy_notebooks/blob/master/Read_OMETIFF_CZI/Read_OMETIFF_or_CZI.py)

The images can be also found on the little [repository](https://github.com/sebi06/ipy_notebooks/tree/master/Read_OMETIFF_CZI) On the Ubuntu system napari also stopped working when used from a jupyter notebook (kernel dies), which is probably the same issue. Again on my windows 10 system it also works fine from the notebook.

Instally vispy by using `pip install -e .` did not change the behavior. It still does not work.

**Comment by jni** [comment]
Thank you @zeissmicroscopy! Looks like a different bug then, which is sad. I use Ubuntu 18.04 on my laptop so I'll investigate in the coming days.

**Comment by sofroniewn** [comment]
Hi @zeissmicroscopy, I'm trying to create a minimal failing example - though I'm on a mac osx so maybe it won't fail there. It looks like the file you failed one was `CellDivision_T=10_Z=15_CH=2_DCV_small.czi` or are you failing on all files you try with this script right now?

I put together this little demo:
```python
import czifile as zis
import numpy as np
import napari

file_name = 'data-njs/zeiss/CellDivision_T=10_Z=15_CH=2_DCV_small.czi'
czi = zis.CziFile(file_name)
cziarray = czi.asarray()
cziarray = np.squeeze(cziarray)
print('czi file shape', cziarray.shape)

with napari.gui_qt():
    napari.view_image(cziarray, channel_axis=1, scale=[1, 3, 1, 1])
```
which is definitely not identical to yours, but at least it worked for me, and your images look great!

<img width="1214" alt="Screen Shot 2019-11-25 at 8 35 10 AM" src="https://user-images.githubusercontent.com/6531703/69559479-def28680-0f5e-11ea-8bae-d6d464372175.png">

I can try reproducing the whole script you sent, but I'm curious if you can tell me more about the behavior and inputs at this line in your demo
```python
# try to configure napari automatically based on metadata
imf.show_napari(array, metadata)
```

What is `array.shape` at that point? If you replace array with `np.random.random(array.shape)` do you still get an error?

What is the contents of metadata? Can you print the dictionary and post in this issue / a link so I can just debug using that dictionary without having to parse the files myself.

Hopefully we can figure this out and get it working for you soon!!

**Comment by cgohlke** [comment]
> on my windows 10 machine and there the code works fine. You can try to reproduce it by using this script:
> Read_OMETIFF_or_CZI.py

Crashes for me on Windows 10. The crash is deep in `Qt5Core.dll` after an exception is raised in [vispy transforms](https://github.com/vispy/vispy/blob/master/vispy/visuals/transforms/_util.py#L80):
```
TypeError: Array shape (1, 5) cannot be converted to vec4
```

**Comment by cgohlke** [comment]
> I'm trying to create a minimal failing example - though I'm on a mac osx so maybe it won't fail there.

Try without squeeze:


```Python
import czifile as zis
import numpy as np
import napari

file_name = 'CellDivision_T=10_Z=15_CH=2_DCV_small.czi'
czi = zis.CziFile(file_name)
cziarray = czi.asarray()
# cziarray = np.squeeze(cziarray)
print('czi file shape', cziarray.shape)

with napari.gui_qt():
    napari.view_image(cziarray, channel_axis=2, scale=[1, 1, 3, 1, 1])
```

**Comment by sofroniewn** [comment]
@cgohlke that doesn't cause a crash for me - I just ran your script and it worked fine.

Looking at that `Array shape (1, 5) cannot be converted to vec4` there are two points that could be causing problems - one is the `scale` keyword arg and that we are accidentally setting scale to be a vector of length 5 and causing a crash - the other is something about the array having singleton dimensions, most likely right at the end - (or maybe a combo of both).

A couple questions:
- If you don't provide the scale keyword arg do you still get the crash?
- Do you still get the crash with `data = np.random.random((1, 10, 2, 15, 256, 256, 1))` (which I think has the same shape as the unsqueezed `cziarray`?
- Do you still get the crash with `data = np.random.random((6, 10, 2, 15, 256, 256, 1))`?
- Do you still get the crash with `data = np.random.random((1, 10, 2, 15, 256, 256, 6))`?
- Do you still get the crash with `data = np.random.random((256, 256, 1))`?

I could be something with how we are treating that last singleton dimension (we are interpreting this data as `rgb` from a napari standpoint I think, but I havn't done extensive testing in this case)

**Comment by cgohlke** [comment]
> that doesn't cause a crash for me

Interesting. Did you try "toggle number of displayed dimensions"?

**Comment by cgohlke** [comment]
>   If you don't provide the scale keyword arg do you still get the crash?

yes

>    Do you still get the crash with data = np.random.random((1, 10, 2, 15, 256, 256, 1)) (which I think has the same shape as the unsqueezed cziarray?

yes

>    Do you still get the crash with data = np.random.random((6, 10, 2, 15, 256, 256, 1))?

yes

>    Do you still get the crash with data = np.random.random((1, 10, 2, 15, 256, 256, 6))?

yes

>    Do you still get the crash with data = np.random.random((256, 256, 1))?

No, that's without `channel_axis` and `scale`.

**Comment by sofroniewn** [comment]
Hmm, none of this stuff crashes for me, including toggling displayed dimensions. Does it crash when you enter `viewer.dims.ndisplay=3` @cgohlke, in which case am I right that the following minimal examples all have the described behavior for you:

```python
import numpy as np
import napari

data = np.random.random((10, 2, 15, 256, 256)) # works
data = np.random.random((256, 256, 1)) # works
data = np.random.random((1, 10, 2, 15, 256, 256, 1)) # crash
data = np.random.random((1, 10, 2, 15, 256, 256, 6)) # crash
data = np.random.random((6, 10, 2, 15, 256, 256, 1)) # crash
data = np.random.random((6, 10, 2, 15, 256, 256, 6)) # ?

with napari.gui_qt():
    napari.view_image(data, ndisplay=3)
```

All these successfully run on my mac osx using the latest napari and the latest vispy on master for both.

**Comment by cgohlke** [comment]
> Does it crash when you enter viewer.dims.ndisplay=3

No, the Traceback is printed on the console.

> using the latest napari and the latest vispy on master for both

I'm using latest released versions. Maybe this issue has been fixed or it's a bug in PyQT5 on Windows?

**Comment by cgohlke** [comment]
> using the latest napari and the latest vispy on master for both

That solves the issue.

**Comment by sofroniewn** [comment]
hmm ok - maybe there are multiple things going on here because @zeissmicroscopy reported up here https://github.com/napari/napari/issues/729#issuecomment-558110759 that the latest vispy / napari on master didn't fix their issue (i.e. wasn't just #576). Maybe I'll let them catch up with the debugging and then see where things are at. We definitely want to get the next napari release out asap and I don't think the next vispy release will be far behind.

Thanks for all the help debugging @cgohlke!!

**Comment by sebi06** [comment]
Hi guys, I checked again and install napari and vispy (in that order) using the latest version from GitHub on my Ubuntu system.

And then I tried to run the following notebook but got stuck again. It is the same issue as when trying this from a script and the error seems to occur here:

`viewer = napari.Viewer()`

But the exact same notebook runs without problems on my windows system. I am not sure if that helps, but let me know if i should try something else.

[Test_Napari_with_CZI.ipynb](https://github.com/sebi06/ipy_notebooks/blob/master/Read_OMETIFF_CZI/Test_Napari_with_CZI.ipynb)




![image](https://user-images.githubusercontent.com/3833249/69752097-cea1fd80-1150-11ea-8720-a4501cae536f.png)

**Comment by sofroniewn** [comment]
If you just run `viewer = napari.Viewer()` in its own cell do you still get a crash? Also, I don't think the `time.sleep(5)` will actually help. We now have code to detect if a `qApp` exists yet and we emit a warning if it doesn't.

Also what happens if you try `%gui qt` and not `%gui qt5` - there could be a weird pyside2 vs pyqt5 conflict going on here

**Comment by sofroniewn** [comment]
Ah also, could be related to the `import ipywidgets as widgets` see #687 though that doesn't seem to be about a seg fault

**Comment by sebi06** [comment]
I removed ipwidgets, switched %gui qt and only tried `viewer = napari.Viewer()` which gave the same result - Kernel died ...

**Comment by sofroniewn** [comment]
yikes. if you just run a brand new, empty notebook with the following two cells

```python
%gui qt
import napari
```

```python
viewer = napari.Viewer()
```
does the kernel still die?

Is there any chance you could be running an old napari - should be `0.2.5` - as we used to have this problem, but fixed it in #642 by emitting a warning when no Qt event loop was detected

**Comment by sebi06** [comment]
I check for my napari and vispy versions and updated both from PyPi.

* Napari = 0.2.6
* Vispy = 0.6.3

The kernel still dies ....

![image](https://user-images.githubusercontent.com/3833249/69829049-c3b59e80-121e-11ea-8eb2-9adbbd977084.png)

**Comment by sofroniewn** [comment]
Interesting - I looks like you have an old version of Qt, see the warning in the cell above, and it’s not getting automatically updated by our pip install. Can you try manually updating your Qt to the minimum version specified in that warning. Can you also put in the thread some specs about the machine you are running from / os version etc

**Comment by sebi06** [comment]
I just created a fresh conda environment and install napari via pip. And them my list of packages does not contain any qt but pyside=5.13.2.

But when I try to start a notebook the errors below when I execute the first cell

```
%gui qt
import napari
```

```
(napari) sebi06@sebastian-tuxedo:~$ jupyter notebook
[I 21:03:42.489 NotebookApp] Serving notebooks from local directory: /datadisk1/tuxedo/Github/ipy_notebooks
[I 21:03:42.489 NotebookApp] The Jupyter Notebook is running at:
[I 21:03:42.489 NotebookApp] http://localhost:8888/?token=6703675f57ffc84c9e53c02b329508adbd8dc8816b053ff6
[I 21:03:42.489 NotebookApp]  or http://127.0.0.1:8888/?token=6703675f57ffc84c9e53c02b329508adbd8dc8816b053ff6
[I 21:03:42.489 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:03:42.504 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/sebi06/.local/share/jupyter/runtime/nbserver-16838-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=6703675f57ffc84c9e53c02b329508adbd8dc8816b053ff6
     or http://127.0.0.1:8888/?token=6703675f57ffc84c9e53c02b329508adbd8dc8816b053ff6
[I 21:03:54.605 NotebookApp] Kernel started: 74092921-9466-477e-b15a-3074468ac75b
[I 21:03:54.961 NotebookApp] Adapting from protocol version 5.1 (kernel 74092921-9466-477e-b15a-3074468ac75b) to 5.3 (client).
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3319, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-e580eceeb872>", line 2, in <module>
    import napari
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/__init__.py", line 29, in <module>
    from .viewer import Viewer
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/viewer.py", line 3, in <module>
    from napari._qt.qt_update_ui import QtUpdateUI
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/_qt/__init__.py", line 1, in <module>
    from .qt_range_slider import QHRangeSlider, QVRangeSlider
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/napari/_qt/qt_range_slider.py", line 316, in <module>
    class QHRangeSlider(QRangeSlider):
TypeError: 'Shiboken.ObjectType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2034, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3242, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3336, in run_code
    self.showtraceback(running_compiled_code=True)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2036, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1384, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1287, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1138, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1084, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 831, in format_records
    frames.append(self.format_record(*r))
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1011, in format_record
    _line_format = PyColorize.Parser(style=col_scheme, parent=self).format2
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 1692, in instance_init
    super(Instance, self).instance_init(obj)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 520, in instance_init
    if (self._dynamic_default_callable(obj) is None) \
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 504, in _dynamic_default_callable
    for cls in mro[:mro.index(self.this_class) + 1]:
AttributeError: type object 'QRangeSlider' has no attribute 'index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2034, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3050, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3261, in run_ast_nodes
    self.showtraceback()
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2036, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1384, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1287, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1138, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1084, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 831, in format_records
    frames.append(self.format_record(*r))
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1011, in format_record
    _line_format = PyColorize.Parser(style=col_scheme, parent=self).format2
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 1692, in instance_init
    super(Instance, self).instance_init(obj)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 520, in instance_init
    if (self._dynamic_default_callable(obj) is None) \
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 504, in _dynamic_default_callable
    for cls in mro[:mro.index(self.this_class) + 1]:
AttributeError: type object 'QRangeSlider' has no attribute 'index'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2034, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'AttributeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 272, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/ipykernel/kernelbase.py", line 539, in execute_request
    reply_content = yield gen.maybe_future(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2847, in run_cell
    result = self._run_cell(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2879, in _run_cell
    self.showtraceback(running_compiled_code=True)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2036, in showtraceback
    stb = self.InteractiveTB.structured_traceback(etype,
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1384, in structured_traceback
    return FormattedTB.structured_traceback(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1287, in structured_traceback
    return VerboseTB.structured_traceback(
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1138, in structured_traceback
    formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1084, in format_exception_as_a_whole
    frames = self.format_records(records, last_unique, recursion_repeat)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 831, in format_records
    frames.append(self.format_record(*r))
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/IPython/core/ultratb.py", line 1011, in format_record
    _line_format = PyColorize.Parser(style=col_scheme, parent=self).format2
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 986, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 977, in setup_instance
    value.instance_init(self)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 1692, in instance_init
    super(Instance, self).instance_init(obj)
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 520, in instance_init
    if (self._dynamic_default_callable(obj) is None) \
  File "/home/sebi06/anaconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py", line 504, in _dynamic_default_callable
    for cls in mro[:mro.index(self.this_class) + 1]:
AttributeError: type object 'QRangeSlider' has no attribute 'index'
```



```
(napari) sebi06@sebastian-tuxedo:~$ conda list
# packages in environment at /home/sebi06/anaconda3/envs/napari:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
babel                     2.7.0                    pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
bleach                    3.1.0                    pypi_0    pypi
ca-certificates           2019.10.16                    0  
certifi                   2019.9.11                py38_0  
chardet                   3.0.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dask                      2.8.1                    pypi_0    pypi
decorator                 4.4.1                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
fasteners                 0.15                     pypi_0    pypi
freetype-py               2.1.0.post1              pypi_0    pypi
fsspec                    0.6.1                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
imageio                   2.6.1                    pypi_0    pypi
imagesize                 1.1.0                    pypi_0    pypi
ipykernel                 5.1.1                    pypi_0    pypi
ipython                   7.10.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.15.1                   pypi_0    pypi
jinja2                    2.10.3                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            5.3.4                    pypi_0    pypi
jupyter-console           6.0.0                    pypi_0    pypi
jupyter-core              4.6.1                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.1.2                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
monotonic                 1.5                      pypi_0    pypi
napari                    0.2.6                    pypi_0    pypi
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  4.4.0                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1  
networkx                  2.4                      pypi_0    pypi
notebook                  6.0.2                    pypi_0    pypi
numcodecs                 0.6.3                    pypi_0    pypi
numpy                     1.17.4                   pypi_0    pypi
numpydoc                  0.9.1                    pypi_0    pypi
openssl                   1.1.1d               h7b6447c_3  
packaging                 19.2                     pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.5.1                    pypi_0    pypi
pexpect                   4.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    6.2.1                    pypi_0    pypi
pip                       19.3.1                   py38_0  
prometheus-client         0.7.1                    pypi_0    pypi
prompt-toolkit            2.0.10                   pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pygments                  2.5.1                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 2.4.5                    pypi_0    pypi
pyrsistent                0.15.6                   pypi_0    pypi
pyside2                   5.13.2                   pypi_0    pypi
python                    3.8.0                h0371630_2  
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyzmq                     18.1.1                   pypi_0    pypi
qtconsole                 4.6.0                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  7.0                  h7b6447c_5  
requests                  2.22.0                   pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scipy                     1.3.3                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                42.0.1                   py38_0  
shiboken2                 5.13.2                   pypi_0    pypi
six                       1.13.0                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    2.2.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
sqlite                    3.30.1               h7b6447c_0  
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
tk                        8.6.8                hbc83047_0  
toolz                     0.10.0                   pypi_0    pypi
tornado                   6.0.3                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
urllib3                   1.25.7                   pypi_0    pypi
vispy                     0.6.3                    pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.6                   py38_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4                h14c3975_4  
zarr                      2.3.2                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  

```

**Comment by sofroniewn** [comment]
Hmm I will look into this more on my laptop. A couple quick things - pyside2 is just the python bindings for the Qt C library that we use, so pyside2 appears in the pip freeze and Qt does not, but you definitely need to have Qt installed somewhere. Normally when installing pyside2 you’ll get the latest qt I think, but I know their are some os dependent variables here.

I also noticed you are using python 3.8 - I’m not sure if that could be the problem, we only test our CI on 3.6 and 3.7

**Comment by kne42** [comment]
Hi @sebi06, I've been getting a bunch of strange `TypeError: 'Shiboken.ObjectType' object is not iterable` errors on Python 3.8 as well. Downgrading to Python 3.7 fixed it for me.

Note: Shiboken is a library used by PySide2, so we will likely need to wait for them to fix this issue for napari to be compatible with Python 3.8.

**Comment by sofroniewn** [comment]
@sebi06 excluding our python 3.8 problems are things now working for you? i've add a specific issue for that #766 that we'll work on. If things are good otherwise I'd like to close this issue

**Comment by sebi06** [comment]
Hi, I completely uninstall everything that had to do with qt from my conda environment and install the latest PyQt5 via pip. And now everything works again, the Napari viewer shows up and displays my 3D stacks nicely. Therefore I close this one.

**Comment by Anushri1903** [comment]
Getting an attribute error when I try to run 
code

import napari
from skimage import data
viewer = napari.view_image(data.moon())

AttributeError: type object 'SubControl' has no attribute 'SC_None'

**Comment by tlambert03** [comment]
hi @Anushri1903, can you create a new issue for that?  and provide us with the output of `napari --info` and `pip list`
