### ISSUE TITLE
[Windows] napari `Toggle Full Screen` results in a glitch with window `Maximize`

### ISSUE THREAD

**Issue by pamitabh** [napari/napari#7300]
### 🐛 Bug Report

I tries to fullscreen napari from the script using `viewer.window._qt_window.showFullScreen()` on windows 11. It did make the window fullscreen and it is responsive but gets stuck on fullscreen, even alt-tab to switch out of it doesn’t work.

I also get the following warning
`WARNING: QWindowsWindow::setGeometry: Unable to set geometry 2562x1082+960+276 (frame: 2578x1121+952+245) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY1". Resulting geometry: 2562x1061+960+276 (frame: 2578x1100+952+245) margins: 8, 31, 8, 8 minimum size: 385x497 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=401,536 maxtrack=0,0)`

it is trying to set the resolution to 2562x1082, which is fishy(!) as my display resolution is 2560x1080.

### 💡 Steps to Reproduce

1. Run:
```
import napari
viewer=napari.Viewer()
viewer.window._qt_window.showFullScreen()
```
2. Try to minimize the napari window.

### 💡 Expected Behavior

I expect the napari window to still respect the os gui controls and minimize, etc. 

### 🌎 Environment

napari: 0.4.19.post1
Platform: Windows-11-10.0.22631-SP0
Python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:20:11) [MSC v.1938 64 bit (AMD64)]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.4
SciPy: 1.13.1
Dask: 2024.5.2
VisPy: 0.14.2
magicgui: 0.8.2
superqt: 0.6.6
in-n-out: 0.2.0
app-model: 0.2.7
npe2: 0.7.5

OpenGL:
- GL version: 4.6.0 NVIDIA 555.99
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1080, scale 1.0

### 💡 Additional Context

I tested this on Ubuntu too, and same as windows it doesn't show the window controls, although I am able to alt-tab out of napari.

**Comment by Czaki** [comment]
Does toggle full-screen shortcut from view menu do not help (I do not have windows to check combination)?

**Comment by psobolewskiPhD** [comment]
Looks like this issue https://bugreports.qt.io/browse/QTBUG-41309

Can you try Alt-Enter to exit? or Control-F? Or F11? Or Control-F11? Do any of those exit?

**Comment by psobolewskiPhD** [comment]
Hmm, it looks like we thought this was fixed!
https://github.com/napari/napari/pull/5401

In fact the code from the fix is what's adding the +2:
https://github.com/napari/napari/blob/c10dc9fe50eb40a648ce4112ec2f7ea0541ed798/napari/_qt/qt_main_window.py#L332-L337
@dalthviz any ideas?

Also I wonder if using pyqt6 would solve this.
Alas, there isn't an easy way to get napari with pyqt6 and everything else, but you could try 
`napari[pyqt6]` to test.

**Comment by jni** [comment]
I'm also curious @pamitabh whether you see the same behaviour on a more recent napari (0.5.3). To be clear, I don't have any specific reason to believe that it will have changed, but I don't want us to be chasing a reproducer when some ancillary fix may have landed in main in the meantime...

**Comment by pamitabh** [comment]
@psobolewskiPhD @Czaki Toggle full screen from the menu bar as well as the Alt-Enter shortcut kinda works:
- It allows alt-tabbing out of napari (still no gui way of doing that - info below)
- dragging away the napari window using mouse still doesn't work
- the gui window control buttons still don't show up (the minimize, maximize, close buttons at top right corner)

As napari window is still responsive I can exit it using ctrl-q or ctrl-w, or using File > close

**Comment by pamitabh** [comment]
> I'm also curious @pamitabh whether you see the same behaviour on a more recent napari (0.5.3). To be clear, I don't have any specific reason to believe that it will have changed, but I don't want us to be chasing a reproducer when some ancillary fix may have landed in main in the meantime...

I tested 0.5.3, same behaviour

**Comment by pamitabh** [comment]
Update: in the newest version of napari (0.5.3) the toggle-fullscreen from gui (view > toggle fullscreen) or alt-enter or script `viewer.window._qt_window.showFullScreen()` leads to the following behavior:

1. If ONLY napari's toggle-fullscreen is used then it behaves fine
[Screencast_napari_nonfullscreen.webm](https://github.com/user-attachments/assets/eaa43d75-bc3f-456d-ae1a-18e92f88f493)

3. If napari's toggle full-screen is combined with the window control maximize then it enters a loop of zooming into napari cutting off its borders
[screencast_fullscreen_napari.webm](https://github.com/user-attachments/assets/34930f20-0b83-4e83-b110-5b9355f24931)

Hopefully these help find the bug..

**Comment by jni** [comment]
> I tested 0.5.3, same behaviour but now I don't get the QWindows warning:

That... That seems worse. 😂 

> the gui window control buttons still don't show up (the minimize, maximize, close buttons at top right corner)

This, though, I think is how fullscreen works in other applications such as games? Fullscreen and maximize are different things and fullscreen does not preserve the window chrome, including borders and window controls. Does this work differently in other applications on Windows 11? (You can use the alt-enter shortcut to check.)

> If napari's toggle full-screen is combined with the window control maximize then it enters a loop of zooming into napari cutting off its borders

This also could be the OS putting the napari window off-screen. I'm not 100% sure whether this is something we can fix. Can you try the same loop (maximize -> Alt-Enter -> Alt-Enter) in other applications, such as Firefox? I remember this sort of thing happening to me with some regularity on Windows.

Either way, as a workaround, can you check whether the suggestions in this article work for you?

https://www.thewindowsclub.com/how-to-move-a-window-when-its-title-bar-goes-off-screen

> - Hold down Alt+Space-bar and then press the M key too. Let go of all the keys.
> - Alternatively, you can also hold Shift down and right-click on the program’s icon in the taskbar, and select Move.
> - You will see your mouse cursor transform into a 4-way arrow and place itself over the window’s title bar.
> - Now use the arrow keys of your keyboard to relocate or move the window.
> - Right-click the mouse when you have moved the window and are done.

There's a few more window management tricks in this article:

https://www.howtogeek.com/310/bring-misplaced-off-screen-windows-back-to-your-desktop-keyboard-trick/

Sorry, I would like to try all this myself but I don't have a Windows PC readily available. I hope the above either helps get you unstuck or helps us diagnose the problem! 🙏

**Comment by pamitabh** [comment]
> This, though, I think is how fullscreen works in other applications such as games? Fullscreen and maximize are different things and fullscreen does not preserve the window chrome, including borders and window controls. Does this work differently in other applications on Windows 11? (You can use the alt-enter shortcut to check.)

yes, I forgot about this and was mixing up 'fullscreen' and 'maximize' in my posts. In the 'fullscreen' the window controls and title bar are hidden but alt-tab still works to switch apps. 

I tried few windows tricks and super (win) + down minimizes the window, nothing else that I tried worked. 

Summarizing and updating the issue: 
1. with napari's fullscreen alt-tab doesn't work to switch between apps. I tried one game and it worked, but maybe there are other apps that this doesn't work with on windows. One can still use View -> Fullscreen to get out of the fullscreen so that is not an issue.

2. Napari window -> Maximize -> Fullscreen, goes into a loop of full-screening the window cutting off borders, check videos in this [post](https://github.com/napari/napari/issues/7300#issuecomment-2381655292). I tested this on Ubuntu linux and it doesn't have this problem, so it is windows specific.

(Please feel free to update the issue title based on these)

**Comment by psobolewskiPhD** [comment]
Thanks for the clarification that with 0.5.3 the issue is the interaction between Windows maximize and napari Full Screen. That makes it a bit more of a corner case, but I think also provides a path to trying to fix it.

If you get a chance, I'd appreciate if you could try a fresh virtual environment with napari installed via `pip install "napari[pyqt6]"`. Would be nice to know for sure that this is due to the bug in Qt5.
❤️

**Comment by dalthviz** [comment]
Hi there, so if I'm following up correctly, the issue here it is now primarly related with the interaction between the application window being maximized, then put on fullscreen and then exiting fullscreen mode, right? From the recordings/videos (thank you so much for those!), seems like the application gets the maximized geometry but it is also being somehow displaced and then you are unable to see the application window frame (and doing it multiple times in a row even can cause the window position to end up also putting the menu bar outside the screen :/). As a workaround for the moment, seems like using the Window + Arrow shorcuts enables you to snap the application window to see again its frame:

https://github.com/user-attachments/assets/10c2b394-7859-4dab-80b9-8ec1ed9f57df

Will give that a check and also will check if there is something that can be done for the alt-tab behavior when activating fullscreen mode.

Checking other Qt6 bindings definitely could be worthy :+1:

**Comment by pamitabh** [comment]
> Thanks for the clarification that with 0.5.3 the issue is the interaction between Windows maximize and napari Full Screen. That makes it a bit more of a corner case, but I think also provides a path to trying to fix it.

That (Maximize and Fullscreen) and the fact that windows is unable to alt-tab out of the Fullscreen. 

@dalthviz : for me on Win 11, the snapping shorcuts don't work only Win + Down arrow works which minimizes the window.

@psobolewskiPhD : I tested with pyqt6, same behavior.
